language: java
jdk:
  - oraclejdk8
  - oraclejdk7
install:
  - mvn -B -Pdeploy -V dependency:go-offline
  - mvn -B -Pdeploy -DexcludeGroupIds=org.eclipse.mylyn.github -V dependency:go-offline
  
script:
   - mvn clean verify
branches:
  only:
    - develop
