language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  - mvn -B -Pdeploy -V dependency:go-offline
  - mvn -B -Pdeploy -DexcludeGroupIds=org.eclipse.mylyn.github -V dependency:go-offline
branches:
  only:
    - develop
