language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  - mvn deploy:deploy-file -DgroupId=org.eclipse.mylyn.github -DartifactId=org.eclipse.egit.github.core -Dversion=3.1.0.201310021548-r -Dpackaging=jar -Dfile=org.eclipse.egit.github.core-3.1.0.201310021548-r.jar -Durl=podam/
  - mvn install
branches:
  only:
    - develop
