 language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  -  mvn install:install-file -DgroupId=org.eclipse.mylyn.github -DartifactId=org.eclipse.egit.github.core -Dversion=3.1.0.201310021548-r -Dpackaging=jar -Dfile=http://dl.bintray.com/typesafe/maven-releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/3.1.0.201310021548-r/org.eclipse.egit.github.core-3.1.0.201310021548-r.jar
branches:
  only:
    - develop
